### ISSUE TITLE
Error when using builderswand

### ISSUE THREAD

**Issue by TheNumenorean** [Matter-Overdrive-Community-Edition/MatterOverdrive-Community-Edition-1.12.2#42]
**Describe the bug**
When using a builders wand there is a chance that the wand vanishes from your hand and an error occurs in the server log.

**To Reproduce**
1. Use the builders wand to place cobble blocks in rows.
2. Notice that the wand vanishes and the given error messages in the log.

**Expected behavior**
To not loose the wand.

**Screenshots**

**please complete the following information:**
 - Forge Version: 2847
 - Mods [e.g. mekanism, optifine]
 - MO Version [e.g. 0.7.4] 0.7.9

**Additional context**
```
net.minecraftforge.event.world.BlockEvent$PlaceEvent@45127d03:
11.05 22:28:44 [Server] INFO java.lang.NullPointerException: null
11.05 22:28:44 [Server] INFO at matteroverdrive.data.quest.logic.AbstractQuestLogicBlock.areBlocksTheSame(AbstractQuestLogicBlock.java:39) ~[AbstractQuestLogicBlock.class:?]
11.05 22:28:44 [Server] INFO at matteroverdrive.data.quest.logic.QuestLogicPlaceBlock.onEvent(QuestLogicPlaceBlock.java:99) ~[QuestLogicPlaceBlock.class:?]
11.05 22:28:44 [Server] INFO at matteroverdrive.data.quest.GenericQuest.onEvent(GenericQuest.java:89) ~[GenericQuest.class:?]
11.05 22:28:44 [Server] INFO at matteroverdrive.data.quest.PlayerQuestData.onEvent(PlayerQuestData.java:133) ~[PlayerQuestData.class:?]
11.05 22:28:44 [Server] INFO at matteroverdrive.entity.player.OverdriveExtendedProperties.onEvent(OverdriveExtendedProperties.java:180) ~[OverdriveExtendedProperties.class:?]
11.05 22:28:44 [Server] INFO at matteroverdrive.handler.BlockHandler.onBlockPlaceEvent(BlockHandler.java:30) ~[BlockHandler.class:?]
11.05 22:28:44 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1310_BlockHandler_onBlockPlaceEvent_PlaceEvent.invoke(.dynamic) ~[?:?]
11.05 22:28:44 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
11.05 22:28:44 [Server] INFO at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67) ~[LagGoggles-1.12.2-5.8-132.jar:?]
11.05 22:28:44 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
11.05 22:28:44 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:178) [ForgeEventFactory.class:?]
11.05 22:28:44 [Server] INFO at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:920) [ForgeHooks.class:?]
11.05 22:28:44 [Server] INFO at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:186) [aip.class:?]
11.05 22:28:44 [Server] INFO at com.rwtema.extrautils2.items.ItemBuildersWand.onItemUseBase(ItemBuildersWand.java:124) [ItemBuildersWand.class:?]
11.05 22:28:44 [Server] INFO at com.rwtema.extrautils2.compatibility.ItemCompat.onItemUse(ItemCompat.java:61) [ItemCompat.class:?]
11.05 22:28:44 [Server] INFO at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:889) [ForgeHooks.class:?]
11.05 22:28:44 [Server] INFO at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:186) [aip.class:?]
11.05 22:28:44 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:492) [or.class:?]
11.05 22:28:44 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741) [pa.class:?]
11.05 22:28:44 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) [ma.class:?]
11.05 22:28:44 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) [ma.class:?]
11.05 22:28:44 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
11.05 22:28:44 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_311]
11.05 22:28:44 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_311]
11.05 22:28:44 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:529) [h.class:?]
11.05 22:28:44 [Server] INFO at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
11.05 22:28:44 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
11.05 22:28:44 [Server] INFO at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
11.05 22:28:44 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
11.05 22:28:44 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_311]
11.05 22:28:44 [Server] Server thread/ERROR [FML]: Index: 6 Listeners:
11.05 22:28:44 [Server] Server thread/ERROR [FML]: 0: NORMAL
11.05 22:28:44 [Server] Server thread/ERROR [FML]: 1: ASM: vazkii.quark.misc.feature.LockDirectionHotkey@7b499527 onBlockPlaced(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
11.05 22:28:44 [Server] Server thread/ERROR [FML]: 2: ASM: vazkii.quark.tweaks.feature.SpongeDriesInNether@212838a onItemPlaced(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
11.05 22:28:44 [Server] Server thread/ERROR [FML]: 3: ASM: INSTANCE onBlockPlace(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
11.05 22:28:44 [Server] Server thread/ERROR [FML]: 4: ASM: mcjty.deepresonance.ForgeEventHandlers@19807e69 onBlockPlaceEvent(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
11.05 22:28:44 [Server] Server thread/ERROR [FML]: 5: ASM: com.buuz135.industrial.proxy.event.SkullHandler@30c933de onBlockPlayerPlace(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
11.05 22:28:44 [Server] Server thread/ERROR [FML]: 6: ASM: matteroverdrive.handler.BlockHandler@75551f0e onBlockPlaceEvent(Lnet/minecraftforge/event/world/BlockEvent$PlaceEvent;)V
11.05 22:28:44 [Server] Server thread/ERROR [FML]: 7: ASM: cr0s.warpdrive.event.WorldHandler@9916d97 onBlockEvent(Lnet/minecraftforge/event/world/BlockEvent;)V
```

**Comment by infiniteblock** [comment]
![image](https://user-images.githubusercontent.com/5800555/167992435-84ab635c-6d8e-4ed8-97b1-afc176c1acc1.png)

I cant seem to reproduce do u have any active quests?

**Comment by TheNumenorean** [comment]
Happened again: 
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException
23.05 18:22:25 [Server] INFO at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_311]
23.05 18:22:25 [Server] INFO at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_311]
23.05 18:22:25 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:531) [h.class:?]
23.05 18:22:25 [Server] INFO at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723) [MinecraftServer.class:?]
23.05 18:22:25 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
23.05 18:22:25 [Server] INFO at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
23.05 18:22:25 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
23.05 18:22:29 [Multicraft] Skipped 6 lines due to rate limit (50/s)
23.05 18:22:29 [Server] INFO at matteroverdrive.entity.player.OverdriveExtendedProperties.onEvent(OverdriveExtendedProperties.java:180) ~[OverdriveExtendedProperties.class:?]
23.05 18:22:29 [Server] INFO at matteroverdrive.handler.BlockHandler.onBlockPlaceEvent(BlockHandler.java:30) ~[BlockHandler.class:?]
23.05 18:22:29 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1310_BlockHandler_onBlockPlaceEvent_PlaceEvent.invoke(.dynamic) ~[?:?]
23.05 18:22:29 [Server] INFO at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
23.05 18:22:29 [Server] INFO at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67) ~[LagGoggles-1.12.2-5.8-132.jar:?]
23.05 18:22:29 [Server] INFO at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
23.05 18:22:29 [Server] INFO at net.minecraftforge.event.ForgeEventFactory.onPlayerBlockPlace(ForgeEventFactory.java:178) ~[ForgeEventFactory.class:?]
23.05 18:22:29 [Server] INFO at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:920) ~[ForgeHooks.class:?]
23.05 18:22:29 [Server] INFO at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:186) ~[aip.class:?]
23.05 18:22:29 [Server] INFO at com.rwtema.extrautils2.items.ItemBuildersWand.onItemUseBase(ItemBuildersWand.java:124) ~[ItemBuildersWand.class:?]
23.05 18:22:29 [Server] INFO at com.rwtema.extrautils2.compatibility.ItemCompat.onItemUse(ItemCompat.java:61) ~[ItemCompat.class:?]
23.05 18:22:29 [Server] INFO at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:889) ~[ForgeHooks.class:?]
23.05 18:22:29 [Server] INFO at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:186) ~[aip.class:?]
23.05 18:22:29 [Server] INFO at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:492) ~[or.class:?]
23.05 18:22:29 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741) ~[pa.class:?]
23.05 18:22:29 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55) ~[ma.class:?]
23.05 18:22:29 [Server] INFO at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11) ~[ma.class:?]
23.05 18:22:29 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
23.05 18:22:29 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_311]
23.05 18:22:31 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_311]
23.05 18:22:31 [Server] INFO at net.minecraft.util.Util.runTask(SourceFile:529) ~[h.class:?]
23.05 18:22:31 [Server] INFO ... 5 more
```
